name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or master, depending on your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, gd, sqlite3
          tools: composer

      - name: Copy .env file
        run: cp env .env

      - name: Install Composer dependencies
        run: composer install --optimize-autoloader

      - name: Configure for SQLite and Set Up Database
        run: |
          # sed -i 's/CI_ENVIRONMENT = .*/CI_ENVIRONMENT = production/g' .env
          sed -i 's/^database\.default\.DBDriver.*/database.default.DBDriver = SQLite3/g' .env
          sed -i 's/^database\.default\.database.*/database.default.database = writable\/database.db/g' .env
          sed -i '/^database\.default\.hostname/s/^/#/' .env
          sed -i '/^database\.default\.username/s/^/#/' .env
          sed -i '/^database\.default\.password/s/^/#/' .env
          sed -i '/^database\.default\.port/s/^/#/' .env
          mkdir -p writable
          mkdir -p writable/cache
          mkdir -p writable/logs
          mkdir -p writable/session
          mkdir -p writable/uploads
          chmod -R 777 writable
          touch writable/database.db
          php spark migrate
          php spark db:seed ShainaPortfolioSeeder

      - name: Start PHP Server
        run: |
          php spark serve >- /dev/null 2>&1 &
          sleep 15

      - name: Create static site directory
        run: mkdir static_site
      
      - name: Fetch the static site
        run: wget --recursive --page-requisites --html-extension --convert-links --domains localhost --no-parent http://localhost:8080/
        # This downloads the site into a folder named 'localhost:8080'

      - name: Move files for deployment
        run: mv localhost:8080/* static_site/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static_site 