name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, gd, sqlite3, pdo_sqlite
          tools: composer

      - name: Copy .env file
        run: cp env .env

      - name: Install Composer dependencies
        run: composer install --optimize-autoloader

      - name: Set up database
        run: |
          sed -i 's/database.default.DBDriver = .*/database.default.DBDriver = SQLite3/' .env
          sed -i 's/# database.default.database = .*/database.default.database = writable\/database.db/' .env
          sed -i 's/database.default.hostname = .*/# database.default.hostname = localhost/' .env
          sed -i 's/database.default.username = .*/# database.default.username = root/' .env
          sed -i 's/database.default.password = .*/# database.default.password = /' .env
          mkdir -p writable/cache
          chmod -R 777 writable
          touch writable/database.db
          php spark migrate
          php spark db:seed ShainaPortfolioSeeder

      - name: Start PHP Server
        run: |
          php spark serve &> server.log &
          sleep 15
      
      - name: Check Server Log
        run: |
          echo "--- Server Log ---"
          cat server.log
          echo "--------------------"

      - name: Crawl site to create static files
        run: |
          mkdir -p static_site
          wget -r -p -E -k -e robots=off --domains localhost --no-parent http://localhost:8080/
          mv localhost:8080/* static_site/
      
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static_site 